version: '3.9'

services:

    # Web Server Service
    nginx:
        build:
            context: ./
            dockerfile: docker2/nginx.docker
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www
            - .docker2/nginx/conf.d/:/etc/docker2/nginx/conf.d/
        depends_on:
            - php-fpm
            - mysql
    mysql:
        image: mysql:8
        volumes:
            - mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
        ports:
            - "3306:3306"

    php-fpm:
        build:
            context: ./
            dockerfile: docker2/php-fpm.docker
        volumes:
            - ./:/var/www
            - .docker2/xDebug/custom.ini:/usr/local/etc/php/conf.d/custom.ini  # Шлях до каталогу з конфігами PHP в контейнері
        extra_hosts:
            - "host.docker.internal:host-gateway"
        links:
            - mysql
        environment:
            DB_PORT: "3306"
            DB_HOST: "mysql"
            XDEBUG_MODE: "debug"
            XDEBUG_CONFIG: "client_host=host.docker.internal idekey=PHPSTORM"
            PHP_IDE_CONFIG: "serverName=localhost"
            XDEBUG_CLIENT_HOST: "host.docker.internal"  # Поправлений на правильний ключ
            XDEBUG_CLIENT_PORT: "9003"

    ### Manticore Search ###########################################
    manticore:
        build:
            context: ./docker2/manticore
        volumes:
            - ./docker2/manticore/config:/etc/manticoresearch
            - ./var/data/manticore/data:/var/lib/manticore/data
            - ./var/data/manticore/log:/var/log/manticore
        ports:
            - "9312:9312"
            - "9306:9306"
            - "9308:9308"
volumes:
    mysql:
        driver: local